version: 0.1

environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Build started on `date`
      - bash toast.sh version
      - bash npm-install.sh
  build:
    commands:
      - echo Nothing to do in the build phase...
  post_build:
    commands:
      - bash lambda.sh
      - bash toast.sh deploy
      - echo Build completed on `date`
artifacts:
  discard-paths: yes
  files:
    - target/*.zip
